image: node:4.4.4

cache:
  paths:
  - node_modules/

all_tests:
  script:
   - npm set progress=false
   - npm install -q --ignore-scripts --unsafe-perm
   - npm bower
   - npm test
   - npm run test-ui