language: node_js
node_js:
  - "4"

sudo: required

services:
  - docker

before_script:
  - sleep 15
  - 'npm install -g bower'
  - 'bower install'

before_deploy
  - 'npm build'

deploy
  - 'npm docker'