language: node_js
node_js:
  - "4"

sudo: false
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - sleep 15
  - 'npm install -g bower grunt-cli'
  - 'bower install'
