version: "2.1"
services:
  web:
    image: nginx
    volumes:
      - "./deployment/nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - bconf
    links:
      - bconf:bconf
    ports:
      - "8080:8080"
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx
    restart: unless-stopped
    command: "nginx -g 'daemon off;'"
  bconf:
    image: bconf:1
    environment:
      ENV NODE_ENV: production
      PORT: 9000
    volumes:
      - /tmp/logs/node-webapp:/tmp/node-logs
    ports:
      - 9000:9000
    links:
      - mongo:mongo
    depends_on:
      mongo:
        condition: service_healthy
    command: node snode
    
  mongo:
    image: mongo:3.4
    ports:
      - 27017
    healthcheck:
        test: ["CMD", "echo", "'db.stats().ok'", "|","mongo","localhost:27017","--quite"]
        interval: 30s
        timeout: 10s
        retries: 5
    volumes:
      - /tmp/mongodb:/data/db

