nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  links:
    - node1:node1
  command: /bin/bash -c "nginx -g 'daemon off;'"
node1:
  # build: .
  image: mangelov/bconf
  environment:
    ENV NODE_ENV: production
    PORT: 9000
  volumes:
    - /tmp/logs/node-webapp:/tmp/node-logs
  ports:
    - "9000"
  links:
    - database
  command: npm start
  #command: forever node server

database:
  image: mongo
  volumes:
    - /opt/db:/data/db

