require('./router')
require('./services/eventBus')
require('./services/connectionManager')

require('./components/welcome.tag')
require('./components/auth/auth.tag')
require('./components/auth/singup.tag')
require('./components/main/main.tag')
require('./components/main/contacts.tag')
require('./components/main/navbar.tag')
require('./components/main/contactItem.tag')
